### ISSUE TITLE
Weird behaviour with bool values

### ISSUE THREAD

**Issue by jacklul** [Nestorboy/NUSaveState#3]
It seems like bool values are bugged and stick to true once set.

Tested this with just one single bool in configuration:
```
- Set testBool = false
- Save
- Load
- testBool = false
- Set testBool = true
- Save
- Load
- testBool = true
- Set testBool = false
- Save
- Load
- testBool = true
```

Tested this with own and pre-build avatar.

**Comment by Nestorboy** [comment]
Thank you for the find!
This issue has been resolved as of commit 540b681fcac1b8f2c28634cc83a255c64e23e3d9, and hopefully there will be a new package later today.
