### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by Godlynerd** [Nestorboy/NUSaveState#6]
you have an avatar prefab there but there is nothing with the avi just the model you are missing some stuff

**Comment by Nestorboy** [comment]
The package comes with a template avatar prefab (`NUSaveState/Avatar/Template/SaveState-Avatar-Template.prefab`) which is used to automatically generate avatar packages you can import into an avatar project and upload to your own account. These avatars are used as data containers for the NUSaveState system.

If you're missing avatar related components on that prefab you should try importing the package again to add the missing components back. Make sure that you've also got the `VRCSDK3A.dll` from the avatar SDK such that the components aren't unidentified.

**Comment by Godlynerd** [comment]
i did what you said and i got everything to work but this 
![Capture](https://github.com/Nestorboy/NUSaveState/assets/147588947/ee3fdbeb-a3fe-48ce-a98f-e8b32fc85825)
also i want to make an exact copy of your savestate avi

**Comment by Godlynerd** [comment]
the asset file in Udon\NUSaveState\Avatar\SOs is the one above

**Comment by Nestorboy** [comment]
Seems like you might be having compilation errors. I would once again make sure to have the `VRCSDK3A.dll` imported into the project before you import anything related to the NUSaveState system.

**Comment by Godlynerd** [comment]
okay i got it to work but on the savestate avi are there any animator controllers or expression menu/parametes

**Comment by Godlynerd** [comment]
this is mine 
![image](https://github.com/Nestorboy/NUSaveState/assets/147588947/d2eedab6-d2f2-42c6-90df-ce4f9467e94e)
this i yours 
![image](https://github.com/Nestorboy/NUSaveState/assets/147588947/5b3306b5-019f-43e0-8d16-44a1395544f3)
i want to make an exact replica avi

**Comment by Godlynerd** [comment]
but i dont know what you did in the animators

**Comment by Nestorboy** [comment]
Based on your previous questions I'm assuming you probably just took the avatar template prefab and pulled it into an avatar project, but I can't say for certain. What you actually want to do is generated an avatar package from the ScriptableObject `Avatar/SOs/Example.asset`, this will spit out a .unitypackage you can import into your avatar package instead, and it will have the appropriate animators and parameters set up for you.

**Comment by Godlynerd** [comment]
i got the save system to work and load i just want to replace the avatar that load all the data that is called savestate-1 and replace it with my own i tried adding my own avi but it does save data

**Comment by Godlynerd** [comment]
i want to recreate the flow control and base layer

**Comment by Nestorboy** [comment]
If you generated that avatar from the `Example.asset` ScriptableObject, then you'll probably have to change the Blueprint ID in that asset actually. After changing the Blueprint ID you should be able to upload the avatar to your account and if you're using the `Example.asset` ScriptableObject in the NUSaveState, then it should update the avatar Blueprint ID there upon building the world too. You could also duplicate the example AvatarData ScriptableObject and change the blueprint on there, but then you'll have to swap out the one it's using in the NUSaveState in the scene.

**Comment by Godlynerd** [comment]
ok thx i finally figured it out
